"""Advanced parser backend — ANTLR COBOL-85 (optional, opt-in).

This is the *full-grammar* path. It activates only when a generated ANTLR COBOL-85
parser is present (see ADVANCED_PARSER.md for the one-time generation step, which needs
Java + the ANTLR tool + the ProLeap COBOL85 grammar). Until then `available()` returns
False and the platform transparently uses the default parser — so nothing breaks.

The adapter contract: `parse(text) -> mip.cobol_ast.Unit`. Whatever full parser you wire
in must populate the same Unit fields (program_id, divisions, paragraphs, data_items,
calls, copies, sql, cics, field_flows, counts, complexity) so the rest of MIP is
unchanged. The advantage of the full grammar is *coverage* — COPY REPLACING expansion,
the complete statement set, nested programs, full CICS — which makes field lineage and
call resolution complete on real-world estates.
"""

from __future__ import annotations


def available() -> bool:
    """True only when both the ANTLR runtime and a generated COBOL85 parser are importable."""
    try:
        import antlr4  # noqa: F401  (antlr4-python3-runtime)
        # Generated by `antlr4 -Dlanguage=Python3 Cobol85.g4` — see ADVANCED_PARSER.md.
        from .grammar.Cobol85Parser import Cobol85Parser  # noqa: F401
        from .grammar.Cobol85Lexer import Cobol85Lexer    # noqa: F401
        return True
    except Exception:
        return False


def parse(text: str):
    """Parse with the ANTLR COBOL-85 grammar and adapt the tree into a mip Unit."""
    if not available():
        raise RuntimeError(
            "Advanced ANTLR backend not available. Generate the grammar (see "
            "ADVANCED_PARSER.md) or unset MIP_PARSER to use the default parser.")

    import antlr4
    from .grammar.Cobol85Lexer import Cobol85Lexer
    from .grammar.Cobol85Parser import Cobol85Parser
    from . import antlr_adapter   # walks the ANTLR tree -> mip Unit (ships with the grammar)

    stream = antlr4.InputStream(antlr_adapter.preprocess(text))   # expands COPY/REPLACING
    parser = Cobol85Parser(antlr4.CommonTokenStream(Cobol85Lexer(stream)))
    tree = parser.startRule()
    return antlr_adapter.to_unit(tree, text)
