"""Advanced parser backend — ANTLR COBOL-85 (optional, opt-in).

This is the *full-grammar* path. It activates only when a generated ANTLR COBOL-85
parser is present (see ADVANCED_PARSER.md for the one-time generation step, which needs
Java + the ANTLR tool + the ProLeap COBOL85 grammar). Until then `available()` returns
False and the platform transparently uses the default parser — so nothing breaks.

The adapter contract: `parse(text) -> mip.cobol_ast.Unit`. Whatever full parser you wire
in must populate the same Unit fields (program_id, divisions, paragraphs, data_items,
calls, copies, sql, cics, field_flows, counts, complexity) so the rest of MIP is
unchanged. The advantage of the full grammar is *coverage* — COPY REPLACING expansion,
the complete statement set, nested programs, full CICS — which makes field lineage and
call resolution complete on real-world estates.
"""

from __future__ import annotations


from antlr4.error.ErrorListener import ErrorListener


class _CollectingErrorListener(ErrorListener):
    def __init__(self) -> None:
        self.errors = []

    def syntaxError(self, recognizer, offendingSymbol, line, column, msg, e):  # noqa: N802
        del recognizer, offendingSymbol, e
        self.errors.append({"line": line, "column": column, "message": msg})


def available() -> bool:
    """True only when both the ANTLR runtime and a generated COBOL85 parser are importable."""
    try:
        import antlr4  # noqa: F401  (antlr4-python3-runtime)
        # Generated by `antlr4 -Dlanguage=Python3 Cobol85.g4` — see ADVANCED_PARSER.md.
        from .grammar.Cobol85Parser import Cobol85Parser  # noqa: F401
        from .grammar.Cobol85Lexer import Cobol85Lexer    # noqa: F401
        return True
    except Exception:
        return False


def _build_tree(pre: str, prediction_mode, *, bail: bool, listener):
    """Lex `pre` and run the COBOL-85 parser under the given ANTLR prediction mode.

    `bail=True` installs BailErrorStrategy so the parse aborts on the first syntax error
    (no recovery overhead) — used for the fast SLL first stage. `listener` (when given)
    collects lexer/parser syntax errors for the exact LL stage."""
    import antlr4
    from .grammar.Cobol85Lexer import Cobol85Lexer
    from .grammar.Cobol85Parser import Cobol85Parser

    stream = antlr4.InputStream(pre)
    lexer = Cobol85Lexer(stream)
    lexer.removeErrorListeners()
    if listener is not None:
        lexer.addErrorListener(listener)
    parser = Cobol85Parser(antlr4.CommonTokenStream(lexer))
    parser.removeErrorListeners()
    if listener is not None:
        parser.addErrorListener(listener)
    parser._interp.predictionMode = prediction_mode
    if bail:
        from antlr4.error.ErrorStrategy import BailErrorStrategy
        parser._errHandler = BailErrorStrategy()
    return parser.startRule()


def parse(text: str, resolver=None, pre: str | None = None):
    """Parse with the ANTLR COBOL-85 grammar and adapt the tree into a mip Unit.

    `resolver(name) -> copybook_text | None` (e.g. antlr_adapter.default_resolver(estate))
    lets the preprocessor expand `COPY ... REPLACING` from real copybooks, so facts hidden
    inside copybooks (record layouts, a CALL behind a REPLACING placeholder) are recovered.
    None -> COPY statements are removed (the COPY edge is still recorded from the raw text).
    `pre` lets the caller pass already-preprocessed text so we don't preprocess twice.

    Two-stage prediction (the standard ANTLR performance recipe): try fast SLL first and
    fall back to exact LL only if SLL can't parse it. For valid input SLL yields the same
    tree as LL at a fraction of the cost; the LL stage preserves the original error
    reporting so genuinely-unparseable members still raise and degrade to the fallback."""
    if not available():
        raise RuntimeError(
            "Advanced ANTLR backend not available. Generate the grammar (see "
            "ADVANCED_PARSER.md) or unset MIP_PARSER to use the default parser.")

    from antlr4 import PredictionMode
    from . import antlr_adapter   # walks the ANTLR tree -> mip Unit (ships with the grammar)

    if pre is None:
        pre = antlr_adapter.preprocess(text, resolver=resolver)   # normalize + expand COPY/REPLACING + fold EXEC

    try:
        tree = _build_tree(pre, PredictionMode.SLL, bail=True, listener=None)
    except Exception:
        listener = _CollectingErrorListener()
        tree = _build_tree(pre, PredictionMode.LL, bail=False, listener=listener)
        if listener.errors:
            raise RuntimeError(f"ANTLR COBOL parse failed: {listener.errors[0]}")
    return antlr_adapter.to_unit(tree, text, pre)
